### ISSUE TITLE
Configuração do Ambiente

### ISSUE THREAD

**Issue by oliveirasWell** [higornucci/dengoso#1]
Olá @higornucci tudo joia?

Você teria um tutorial de como configurar o ambiente, que sevlet você está usando, se está usando algum framework e etc?

Obrigado.

**Comment by higornucci** [comment]
Olá, Wellington.

Acabei de atualizar o Readme.md do projeto com as instruções para rodar o projeto em sua máquina.

Basta ir até a página inicial do repositório e seguir os passos que estão lá.
Aqui vai uma ajudinha para ir até os [primeiro passos](https://github.com/higornucci/patrulhadadengue-web).
